#!/usr/bin/env node
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { buildSite } from "./lib/site.mjs";

/**
 * Living-Documentation site generator (RFC 0004).
 *
 * Renders the public requirements (exoas-exo-reqs submodule) + ADRs (.archgate)
 * + ontology reference (exoas-exo submodule) of kitelev/exocortex into a static
 * site. Reads ONLY local checked-out paths — no network. Self-contained: no
 * dependency on @kitelev/exocortex-cli.
 *
 * Usage:
 *   node docs-site/build.mjs [--reqs <dir>] [--archgate <dir>] \
 *        [--ontology <dir>] [--out <dir>]
 *
 * Defaults resolve to this repo's submodule layout, so a bare
 * `node docs-site/build.mjs` works from a fresh `submodules: recursive` checkout.
 */

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--reqs") out.reqs = argv[++i];
    else if (a === "--archgate") out.archgate = argv[++i];
    else if (a === "--ontology") out.ontology = argv[++i];
    else if (a === "--out") out.out = argv[++i];
    else if (a === "--help" || a === "-h") out.help = true;
    else {
      console.error(`Unknown argument: ${a}`);
      out.help = true;
    }
  }
  return out;
}

function usage() {
  console.log(
    `Living-Documentation site generator (RFC 0004)

  node docs-site/build.mjs [options]

  --reqs <dir>      requirements ABox       (default: packages/exoas-exo-reqs/exo-reqs)
  --archgate <dir>  .archgate directory     (default: .archgate)
  --ontology <dir>  ontology submodule      (default: packages/exoas-exo)
  --out <dir>       output site directory   (default: _site)
`,
  );
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    usage();
    return 0;
  }
  const opts = {
    reqs: args.reqs ?? join(REPO_ROOT, "packages/exoas-exo-reqs/exo-reqs"),
    archgate: args.archgate ?? join(REPO_ROOT, ".archgate"),
    ontology: args.ontology ?? join(REPO_ROOT, "packages/exoas-exo"),
    out: args.out ?? join(REPO_ROOT, "_site"),
    generatedNote:
      "Generated by docs-site/build.mjs from the graph (RFC 0004). All content is sourced from public submodules of kitelev/exocortex.",
  };
  const r = await buildSite(opts);
  console.log(
    `[living-docs] built ${r.files} files → ${opts.out}\n` +
      `  requirements: ${r.requirements} (${Math.round(r.coverage * 100)}% covered)\n` +
      `  ADRs:         ${r.adrs}\n` +
      `  ontology:     ${r.ontologyTerms} terms`,
  );
  return 0;
}

main()
  .then((code) => process.exit(code ?? 0))
  .catch((err) => {
    console.error("[living-docs] build failed:", err?.stack ?? err);
    process.exit(1);
  });
