#!/usr/bin/env tsx
/**
 * flaky-pr-comment.ts — RFC Phase 3.4 / T4.3
 *
 * Builds a post-merge PR-comment widget surfacing the rolling flaky / rerun
 * rate snapshot. Runs after squash-merges into `main` (see
 * .github/workflows/flaky-pr-comment.yml).
 *
 * Pipeline:
 *   1. Resolve the merged PR number from the merge-commit SHA.
 *   2. List the last 2*window completed `ci.yml` runs on main.
 *   3. Download `flaky-*` artifacts for each run, group by run id.
 *   4. Aggregate twice (current = newest window, prior = window before that)
 *      via the pure helper exported by flaky-aggregate.ts.
 *   5. Render a sticky markdown comment body (idempotent — see STICKY_MARKER).
 *   6. Emit body to stdout / `--output` so the workflow step can POST/PATCH it.
 *
 * The script never edits comments itself — that is delegated to the workflow
 * (gh api), which keeps the script side-effect-free except for filesystem
 * writes when `--output` is provided.
 *
 * Usage from monorepo root:
 *   npx tsx packages/obsidian-plugin/scripts/flaky-pr-comment.ts \
 *     --repo kitelev/exocortex --pr 1234 --window 30 --output body.md
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { spawnSync } from "node:child_process";

import {
  aggregate,
  downloadFlakyArtifacts,
  listRuns,
  readReportsFromDir,
  type AggregateInput,
  type AggregateOutput,
} from "./flaky-aggregate";

export const STICKY_MARKER = "<!-- exocortex-flaky-widget:v1 -->";

export interface PRCommentInput {
  current: AggregateOutput;
  prior: AggregateOutput;
  pullNumber: number;
  topN: number;
  marker?: string;
}

export interface TrendDelta {
  delta: number;
  arrow: string;
  label: string;
}

/**
 * Pull-request number embedded in a squash-merge commit subject like
 * "feat: foo (#1234)". Returns null when no `(#N)` token is present.
 */
export function extractPullNumberFromCommit(message: string): number | null {
  if (!message) return null;
  // Last occurrence wins — squash subject ends with "(#N)" but body may
  // mention other PRs. Scanning from the right is more robust than `.match`.
  const matches = Array.from(message.matchAll(/\(#(\d+)\)/g));
  if (matches.length === 0) return null;
  const last = matches[matches.length - 1];
  return Number(last[1]);
}

const FLAT_THRESHOLD_PP = 0.5;

export function formatTrendDelta(
  currentPct: number,
  priorPct: number,
): TrendDelta {
  const delta = Number((currentPct - priorPct).toFixed(2));
  if (delta > FLAT_THRESHOLD_PP) {
    return { delta, arrow: "↑", label: "worse" };
  }
  if (delta < -FLAT_THRESHOLD_PP) {
    return { delta, arrow: "↓", label: "better" };
  }
  return { delta, arrow: "→", label: "flat" };
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function signed(n: number): string {
  return n >= 0 ? `+${n}` : `${n}`;
}

export function renderPRComment(input: PRCommentInput): string {
  const { current, prior, pullNumber, topN } = input;
  const marker = input.marker ?? STICKY_MARKER;
  const trend = formatTrendDelta(
    current.summary.rerunRatePercent,
    prior.summary.rerunRatePercent,
  );
  const top = current.perSpec.slice(0, topN);

  const lines: string[] = [];
  lines.push(marker);
  lines.push(`### 🧪 Flaky-rate snapshot (RFC Phase 3.4)`);
  lines.push("");
  lines.push(
    `**PR #${pullNumber}** merged into \`main\`. Rolling window = ${current.rollingWindow.actualSize} run${current.rollingWindow.actualSize === 1 ? "" : "s"}.`,
  );
  lines.push("");
  lines.push(
    `| Metric | Current (last ${current.rollingWindow.actualSize}) | Prior (${prior.rollingWindow.actualSize} before) | Δ |`,
  );
  lines.push(`| --- | --- | --- | --- |`);
  lines.push(
    `| Rerun rate | ${current.summary.rerunRatePercent}% | ${prior.summary.rerunRatePercent}% | ${trend.arrow} ${signed(trend.delta)} pp (${trend.label}) |`,
  );
  lines.push(
    `| Avg flaky / run | ${current.summary.averageFlakyPerRun} | ${prior.summary.averageFlakyPerRun} | — |`,
  );
  lines.push(
    `| Runs with flaky | ${current.summary.runsWithFlaky}/${current.summary.totalRuns} | ${prior.summary.runsWithFlaky}/${prior.summary.totalRuns} | — |`,
  );
  lines.push("");
  if (top.length === 0) {
    lines.push(`✅ **No flaky offenders in current window.**`);
  } else {
    lines.push(
      `#### Top-${top.length} offender${top.length > 1 ? "s" : ""} (current window)`,
    );
    lines.push("");
    lines.push(`| # | Spec | Title | Occurrences | Rerun rate |`);
    lines.push(`| - | ---- | ----- | ----------- | ---------- |`);
    top.forEach((s, i) => {
      lines.push(
        `| ${i + 1} | \`${escapeCell(s.file)}\` | ${escapeCell(s.title)} | ${s.occurrences} | ${s.rerunRate}% |`,
      );
    });
  }
  lines.push("");
  lines.push(
    `<sub>Generated by \`.github/workflows/flaky-pr-comment.yml\` · aggregator \`packages/obsidian-plugin/scripts/flaky-aggregate.ts\` · RFC §3.4 / T4.3 · sticky comment (edited in place on every merge).</sub>`,
  );
  return lines.join("\n") + "\n";
}

// -----------------------------------------------------------------------------
// CLI
// -----------------------------------------------------------------------------

export interface PRCommentCliOptions {
  repo: string;
  workflow: string;
  branch: string;
  window: number;
  topN: number;
  pullNumber: number | null;
  commitSha: string | null;
  commitMessage: string | null;
  output: string | null;
  dryRun: boolean;
  inputCurrent: string | null;
  inputPrior: string | null;
}

export function parsePRCommentArgs(argv: string[]): PRCommentCliOptions {
  const opts: PRCommentCliOptions = {
    repo: "kitelev/exocortex",
    workflow: "ci.yml",
    branch: "main",
    window: 30,
    topN: 3,
    pullNumber: null,
    commitSha: null,
    commitMessage: null,
    output: null,
    dryRun: false,
    inputCurrent: null,
    inputPrior: null,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => argv[++i];
    switch (arg) {
      case "--repo":
        opts.repo = next();
        break;
      case "--workflow":
        opts.workflow = next();
        break;
      case "--branch":
        opts.branch = next();
        break;
      case "--window":
        opts.window = Number(next());
        break;
      case "--top":
        opts.topN = Number(next());
        break;
      case "--pr":
      case "--pull":
        opts.pullNumber = Number(next());
        break;
      case "--sha":
        opts.commitSha = next();
        break;
      case "--commit-message":
        opts.commitMessage = next();
        break;
      case "--output":
      case "-o":
        opts.output = next();
        break;
      case "--input-current":
        opts.inputCurrent = next();
        break;
      case "--input-prior":
        opts.inputPrior = next();
        break;
      case "--dry-run":
        opts.dryRun = true;
        break;
      case "--help":
      case "-h":
        printUsage();
        process.exit(0);
        break;
      default:
        if (arg.startsWith("--")) {
          throw new Error(`Unknown flag: ${arg}`);
        }
    }
  }
  if (!Number.isFinite(opts.window) || opts.window <= 0) {
    throw new Error(`--window must be a positive integer, got: ${opts.window}`);
  }
  if (!Number.isFinite(opts.topN) || opts.topN <= 0) {
    throw new Error(`--top must be a positive integer, got: ${opts.topN}`);
  }
  return opts;
}

function printUsage(): void {
  console.log(`Usage: flaky-pr-comment.ts [options]

Options:
  --repo <slug>            owner/repo (default: kitelev/exocortex)
  --workflow <file>        workflow filename (default: ci.yml)
  --branch <name>          branch to scan (default: main)
  --window <N>             rolling window size, runs per cohort (default: 30)
  --top <N>                top-N offenders to render (default: 3)
  --pr, --pull <N>         pull-request number (preferred over --sha)
  --sha <hash>             merge commit SHA — used to resolve PR via gh api
  --commit-message <text>  fallback PR resolution via "(#N)" extraction
  --output, -o <path>      write rendered body to file (else stdout)
  --input-current <path>   pre-aggregated JSON for current window (skips gh)
  --input-prior <path>     pre-aggregated JSON for prior window (skips gh)
  --dry-run                skip artifact downloads (for CI smoke tests)
  --help, -h               show this help
`);
}

function gh(args: string[]): string {
  const proc = spawnSync("gh", args, {
    encoding: "utf-8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (proc.status !== 0) {
    throw new Error(
      `gh ${args.join(" ")} failed (exit ${proc.status}): ${proc.stderr}`,
    );
  }
  return proc.stdout;
}

export function resolvePullNumber(
  opts: Pick<
    PRCommentCliOptions,
    "pullNumber" | "commitSha" | "commitMessage" | "repo"
  >,
): number | null {
  if (opts.pullNumber && opts.pullNumber > 0) return opts.pullNumber;
  if (opts.commitMessage) {
    const fromMsg = extractPullNumberFromCommit(opts.commitMessage);
    if (fromMsg) return fromMsg;
  }
  if (opts.commitSha) {
    try {
      const json = gh([
        "api",
        `repos/${opts.repo}/commits/${opts.commitSha}/pulls`,
        "--jq",
        ".[0].number",
      ]);
      const n = Number(json.trim());
      if (Number.isFinite(n) && n > 0) return n;
    } catch (err) {
      console.warn(
        `[warn] gh api commit→pulls failed: ${(err as Error).message}`,
      );
    }
  }
  return null;
}

function loadJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
}

function aggregateRange(
  input: AggregateInput,
  window: number,
): AggregateOutput {
  return aggregate(input, window);
}

export function collectWindows(opts: PRCommentCliOptions): {
  current: AggregateOutput;
  prior: AggregateOutput;
} {
  if (opts.inputCurrent && opts.inputPrior) {
    return {
      current: loadJson<AggregateOutput>(opts.inputCurrent),
      prior: loadJson<AggregateOutput>(opts.inputPrior),
    };
  }
  const totalLimit = opts.window * 2;
  const runs = listRuns(opts.repo, opts.workflow, opts.branch, totalLimit);
  if (opts.dryRun) {
    console.log(
      `[dry-run] would download flaky artifacts for ${runs.length} runs`,
    );
    const empty: AggregateInput = { runs: [] };
    return {
      current: aggregateRange(empty, opts.window),
      prior: aggregateRange(empty, opts.window),
    };
  }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "flaky-pr-comment-"));
  try {
    const collected: AggregateInput["runs"] = runs.map((meta) => {
      const runDir = path.join(tmp, String(meta.runId));
      downloadFlakyArtifacts(opts.repo, meta.runId, runDir);
      return { meta, reports: readReportsFromDir(runDir) };
    });
    const currentSlice = collected.slice(0, opts.window);
    const priorSlice = collected.slice(opts.window, opts.window * 2);
    return {
      current: aggregateRange({ runs: currentSlice }, opts.window),
      prior: aggregateRange({ runs: priorSlice }, opts.window),
    };
  } finally {
    try {
      fs.rmSync(tmp, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
}

export function runPRCommentCli(argv: string[]): void {
  const opts = parsePRCommentArgs(argv);
  const pullNumber = resolvePullNumber(opts);
  if (!pullNumber) {
    console.warn(
      "flaky-pr-comment: could not resolve PR number — skipping (provide --pr / --sha / --commit-message).",
    );
    process.exit(0);
  }
  const { current, prior } = collectWindows(opts);
  const body = renderPRComment({
    current,
    prior,
    pullNumber,
    topN: opts.topN,
  });
  if (opts.output) {
    fs.mkdirSync(path.dirname(path.resolve(opts.output)), { recursive: true });
    fs.writeFileSync(opts.output, body, "utf-8");
    console.log(
      `flaky-pr-comment: wrote ${opts.output} (PR #${pullNumber}, current=${current.summary.rerunRatePercent}%, prior=${prior.summary.rerunRatePercent}%)`,
    );
  } else {
    process.stdout.write(body);
  }
}

function isInvokedAsScript(): boolean {
  const entry = process.argv[1] ?? "";
  return /flaky-pr-comment\.[mc]?[tj]s$/.test(entry);
}

if (isInvokedAsScript()) {
  try {
    runPRCommentCli(process.argv.slice(2));
  } catch (err) {
    console.error(`flaky-pr-comment failed: ${(err as Error).message}`);
    process.exit(1);
  }
}
