#!/usr/bin/env tsx
/**
 * flaky-render-markdown.ts — RFC Phase 3.4 / T4.2
 *
 * Reads the structured JSON produced by flaky-aggregate.ts (T4.1) and emits a
 * human-readable markdown dashboard at packages/obsidian-plugin/docs/
 * FLAKY_DASHBOARD.md. Picked up by the weekly cron in
 * .github/workflows/flaky-dashboard.yml and auto-committed on main.
 *
 * Sections rendered:
 *   1. Snapshot — generatedAt, rolling window, rerun rate, totals.
 *   2. Trend — sparkline of totalFlaky per run across the rolling window.
 *   3. Top-10 offenders — by occurrences, with rerun rate %.
 *   4. Per-shard breakdown — runs touched and flaky count per shard.
 *   5. Per-run timeline — last N runs with conclusion + flaky count.
 *
 * Run from monorepo root:
 *   npx tsx packages/obsidian-plugin/scripts/flaky-render-markdown.ts \
 *     --input packages/obsidian-plugin/docs/FLAKY_DASHBOARD.json \
 *     --output packages/obsidian-plugin/docs/FLAKY_DASHBOARD.md
 */
import * as fs from "node:fs";
import * as path from "node:path";

export interface RenderInput {
  generatedAt: string;
  schemaVersion: number;
  rollingWindow: {
    requestedSize: number;
    actualSize: number;
    runIds: number[];
  };
  summary: {
    totalRuns: number;
    runsWithFlaky: number;
    totalFlakyOccurrences: number;
    averageFlakyPerRun: number;
    rerunRatePercent: number;
  };
  perSpec: Array<{
    file: string;
    title: string;
    occurrences: number;
    rerunRate: number;
    sources: string[];
  }>;
  perShard: Record<string, { runs: number; flaky: number }>;
  perRun: Array<{
    runId: number;
    createdAt: string;
    conclusion: string;
    headSha: string;
    totalFlaky: number;
    sources: string[];
  }>;
}

export interface RenderCliOptions {
  input: string;
  output: string;
  topN: number;
  repo: string;
}

export function parseRenderArgs(argv: string[]): RenderCliOptions {
  const opts: RenderCliOptions = {
    input: "packages/obsidian-plugin/docs/FLAKY_DASHBOARD.json",
    output: "packages/obsidian-plugin/docs/FLAKY_DASHBOARD.md",
    topN: 10,
    repo: "kitelev/exocortex",
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => argv[++i];
    switch (arg) {
      case "--input":
      case "-i":
        opts.input = next();
        break;
      case "--output":
      case "-o":
        opts.output = next();
        break;
      case "--top":
        opts.topN = Number(next());
        break;
      case "--repo":
        opts.repo = next();
        break;
      case "--help":
      case "-h":
        printRenderUsage();
        process.exit(0);
        break;
      default:
        if (arg.startsWith("--")) {
          throw new Error(`Unknown flag: ${arg}`);
        }
    }
  }
  if (!Number.isFinite(opts.topN) || opts.topN <= 0) {
    throw new Error(`--top must be a positive integer, got: ${opts.topN}`);
  }
  return opts;
}

function printRenderUsage(): void {
  console.log(`Usage: flaky-render-markdown.ts [options]

Options:
  --input, -i <path>   aggregate JSON path (default: FLAKY_DASHBOARD.json)
  --output, -o <path>  markdown output path (default: FLAKY_DASHBOARD.md)
  --top <N>            top-N offenders to render (default: 10)
  --repo <slug>        owner/repo for run links (default: kitelev/exocortex)
  --help, -h           show this help
`);
}

const SPARKLINE_BLOCKS = ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"];

export function sparkline(values: number[]): string {
  if (values.length === 0) return "";
  const max = Math.max(...values);
  if (max === 0) {
    return SPARKLINE_BLOCKS[0].repeat(values.length);
  }
  return values
    .map((v) => {
      const idx = Math.min(
        SPARKLINE_BLOCKS.length - 1,
        Math.max(0, Math.round((v / max) * (SPARKLINE_BLOCKS.length - 1))),
      );
      return SPARKLINE_BLOCKS[idx];
    })
    .join("");
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function shortSha(sha: string): string {
  return sha ? sha.slice(0, 7) : "—";
}

function fmtDate(iso: string): string {
  if (!iso) return "—";
  // YYYY-MM-DD HH:MM UTC
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ` +
    `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`
  );
}

export function renderMarkdown(data: RenderInput, opts: RenderCliOptions): string {
  const lines: string[] = [];
  lines.push("# Flaky Test Dashboard");
  lines.push("");
  lines.push(
    "> Auto-generated by `.github/workflows/flaky-dashboard.yml` (RFC Phase 3.4 / T4.2). " +
      "Do not edit manually — changes will be overwritten on the next weekly run.",
  );
  lines.push("");

  // 1. Snapshot
  lines.push("## Snapshot");
  lines.push("");
  lines.push(`- **Generated at:** ${fmtDate(data.generatedAt)}`);
  lines.push(
    `- **Rolling window:** ${data.rollingWindow.actualSize} / ${data.rollingWindow.requestedSize} runs`,
  );
  lines.push(`- **Total runs analyzed:** ${data.summary.totalRuns}`);
  lines.push(
    `- **Runs with flaky tests:** ${data.summary.runsWithFlaky} ` +
      `(${data.summary.rerunRatePercent}% rerun rate)`,
  );
  lines.push(
    `- **Total flaky occurrences:** ${data.summary.totalFlakyOccurrences}`,
  );
  lines.push(
    `- **Average flaky/run:** ${data.summary.averageFlakyPerRun}`,
  );
  lines.push("");

  // 2. Trend
  lines.push("## Trend (oldest → newest)");
  lines.push("");
  if (data.perRun.length === 0) {
    lines.push("_No runs in window._");
    lines.push("");
  } else {
    // perRun is sorted newest-first by aggregator; reverse for chronological view.
    const chrono = [...data.perRun].reverse();
    const values = chrono.map((r) => r.totalFlaky);
    const max = values.length ? Math.max(...values) : 0;
    const spark = sparkline(values);
    lines.push("```");
    lines.push(`flaky/run  ${spark}`);
    lines.push(
      `min=${Math.min(...values)}  max=${max}  n=${values.length}`,
    );
    lines.push("```");
    lines.push("");
  }

  // 3. Top-N offenders
  lines.push(`## Top-${opts.topN} Offenders`);
  lines.push("");
  if (data.perSpec.length === 0) {
    lines.push("_No flaky specs in window._");
    lines.push("");
  } else {
    lines.push("| # | File | Test | Occurrences | Rerun rate |");
    lines.push("|---|------|------|------------:|-----------:|");
    data.perSpec.slice(0, opts.topN).forEach((s, i) => {
      lines.push(
        `| ${i + 1} | \`${escapeCell(s.file)}\` | ${escapeCell(s.title) || "—"} | ${s.occurrences} | ${s.rerunRate}% |`,
      );
    });
    lines.push("");
  }

  // 4. Per-shard
  lines.push("## Per-Shard Breakdown");
  lines.push("");
  const shardEntries = Object.entries(data.perShard);
  if (shardEntries.length === 0) {
    lines.push("_No shard-tagged sources in window._");
    lines.push("");
  } else {
    lines.push("| Shard | Runs touched | Flaky occurrences |");
    lines.push("|-------|-------------:|------------------:|");
    for (const [shard, stats] of shardEntries) {
      lines.push(`| ${shard} | ${stats.runs} | ${stats.flaky} |`);
    }
    lines.push("");
  }

  // 5. Per-run timeline (most recent first)
  lines.push(`## Run Timeline (last ${data.perRun.length})`);
  lines.push("");
  if (data.perRun.length === 0) {
    lines.push("_No runs available._");
    lines.push("");
  } else {
    lines.push("| Run | Created | SHA | Conclusion | Flaky |");
    lines.push("|-----|---------|-----|------------|------:|");
    for (const r of data.perRun) {
      const link = `[${r.runId}](https://github.com/${opts.repo}/actions/runs/${r.runId})`;
      lines.push(
        `| ${link} | ${fmtDate(r.createdAt)} | \`${shortSha(r.headSha)}\` | ${r.conclusion} | ${r.totalFlaky} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

export function runRenderCli(argv: string[]): void {
  const opts = parseRenderArgs(argv);
  const inputPath = path.resolve(opts.input);
  if (!fs.existsSync(inputPath)) {
    throw new Error(`Input JSON not found: ${inputPath}`);
  }
  const raw = fs.readFileSync(inputPath, "utf-8");
  const data = JSON.parse(raw) as RenderInput;
  const md = renderMarkdown(data, opts);
  const outPath = path.resolve(opts.output);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, md, "utf-8");
  console.log(
    `flaky-render-markdown: wrote ${outPath} ` +
      `(${data.summary.totalRuns} runs, ${data.perSpec.length} unique specs)`,
  );
}

function isInvokedAsScript(): boolean {
  const entry = process.argv[1] ?? "";
  return /flaky-render-markdown\.[mc]?[tj]s$/.test(entry);
}

if (isInvokedAsScript()) {
  try {
    runRenderCli(process.argv.slice(2));
  } catch (err) {
    console.error(
      `flaky-render-markdown failed: ${(err as Error).message}`,
    );
    process.exit(1);
  }
}
