import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import esbuildPluginTsc from "esbuild-plugin-tsc";

const banner = `/* Generated by esbuild - source: github.com/kitelev/exocortex */
`;

const prod = process.argv[2] === "production";
const isDev = !prod;

// Performance optimization plugins
const performancePlugin = {
  name: "performance-optimizer",
  setup(build) {
    let buildStart = 0;
    
    build.onStart(() => {
      buildStart = Date.now();
      if (isDev) {
        console.log("🚀 Starting optimized build...");
      }
    });

    build.onEnd((result) => {
      const buildTime = Date.now() - buildStart;
      
      if (isDev) {
        console.log(`✅ Build completed in ${buildTime}ms`);
        
        // Performance warnings
        if (buildTime > 5000) {
          console.warn(`⚠️  Build time ${buildTime}ms is above optimal threshold (5000ms)`);
        }
      }

      // Bundle size analysis
      if (result.metafile) {
        const bundleSize = fs.statSync(build.initialOptions.outfile).size;
        const bundleSizeMB = (bundleSize / 1024 / 1024).toFixed(2);
        
        if (isDev) {
          console.log(`📦 Bundle size: ${bundleSizeMB}MB`);
        }
        
        // Size warnings
        if (bundleSize > 2 * 1024 * 1024) { // 2MB
          console.warn(`⚠️  Bundle size ${bundleSizeMB}MB exceeds recommended limit (2MB)`);
        }
      }
    });
  }
};

// Development-specific optimizations
const devOptimizationsPlugin = {
  name: "dev-optimizations",
  setup(build) {
    if (!isDev) return;

    // Hot reload optimizations
    build.onResolve({ filter: /^obsidian$/ }, (args) => {
      // Cache obsidian module resolution for faster rebuilds
      return { path: args.path, external: true };
    });

    // Skip unnecessary transforms in development
    build.onLoad({ filter: /\.ts$/ }, async (args) => {
      // Skip type checking in dev mode for speed
      if (args.path.includes('node_modules')) {
        return null; // Let esbuild handle it normally
      }
      
      // For source files, we can add development-specific optimizations
      return null; // Let esbuild handle normally for now
    });
  }
};

// Incremental build cache
const cachePlugin = {
  name: "cache-optimizer",
  setup(build) {
    const cacheDir = ".esbuild-cache";
    
    if (isDev && !fs.existsSync(cacheDir)) {
      fs.mkdirSync(cacheDir, { recursive: true });
    }

    build.onStart(() => {
      if (isDev) {
        // Clean old cache files (older than 1 day)
        const oneDayAgo = Date.now() - 24 * 60 * 60 * 1000;
        
        try {
          const files = fs.readdirSync(cacheDir);
          files.forEach(file => {
            const filePath = path.join(cacheDir, file);
            const stats = fs.statSync(filePath);
            
            if (stats.mtime.getTime() < oneDayAgo) {
              fs.unlinkSync(filePath);
            }
          });
        } catch (error) {
          // Ignore cache cleanup errors
        }
      }
    });
  }
};

// Environment-specific configuration
const baseConfig = {
  banner: {
    js: banner,
  },
  entryPoints: ["packages/obsidian-plugin/src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  platform: "browser", // Browser platform for proper module resolution
  target: "es2020",
  logLevel: isDev ? "info" : "warning",
  treeShaking: true,
  outfile: "packages/obsidian-plugin/main.js",
  // Preact aliases for massive bundle size reduction
  // Path aliases for cleaner imports
  alias: {
    'react': 'preact/compat',
    'react-dom': 'preact/compat',
    'react/jsx-runtime': 'preact/jsx-runtime',
    // Replace full reflect-metadata (24 KB) with minimal shim (~400 bytes)
    // TSyringe only uses: Reflect.getMetadata, getOwnMetadata, defineMetadata
    'reflect-metadata': './packages/obsidian-plugin/src/infrastructure/reflect-metadata-shim.ts',
    '@plugin/types': './packages/obsidian-plugin/src/types/index.ts',
    '@plugin/adapters': './packages/obsidian-plugin/src/adapters',
    '@plugin/application': './packages/obsidian-plugin/src/application',
    '@plugin/domain': './packages/obsidian-plugin/src/domain',
    '@plugin/infrastructure': './packages/obsidian-plugin/src/infrastructure',
    '@plugin/presentation': './packages/obsidian-plugin/src/presentation',
  },
  charset: 'utf8', // Avoid unnecessary Unicode escaping in string literals
  plugins: [
    esbuildPluginTsc(), // CRITICAL: Uses actual TypeScript compiler to emit decorator metadata for TSyringe DI
    performancePlugin,
    cachePlugin,
    ...(isDev ? [devOptimizationsPlugin] : [])
  ]
};

// Production optimizations
const productionConfig = {
  ...baseConfig,
  // Full minification including identifier mangling.
  // TSyringe DI resolves via design:paramtypes metadata (class references),
  // NOT via constructor .name strings. Token-based registration in container.ts
  // uses DI_TOKENS which are string constants, not class names.
  // Therefore keepNames is not required for DI — only affects error messages.
  minify: true,
  sourcemap: false,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  // Advanced production optimizations
  metafile: true,
  // Drop debug code in production
  drop: ["console", "debugger"],
  // Additional size optimizations
  legalComments: "none", // Remove license comments to save space
  pure: ["console.log", "console.debug", "console.info"], // Mark as pure for tree-shaking
  ignoreAnnotations: false, // Respect pure annotations
};

// Development optimizations
const developmentConfig = {
  ...baseConfig,
  sourcemap: "inline",
  define: {
    "process.env.NODE_ENV": '"development"',
  },
  // Development-specific optimizations
  incremental: true,
  write: true,
  // Keep names for better debugging
  keepNames: true,
  // Faster builds
  minify: false,
  // Source map optimizations
  sourceRoot: "src/",
  sourcesContent: true
};

const finalConfig = prod ? productionConfig : developmentConfig;

// Performance monitoring
const startTime = Date.now();

try {
  const context = await esbuild.context(finalConfig);

  if (prod) {
    console.log("🏗️  Building for production...");
    const result = await context.rebuild();

    if (result.metafile) {
      // Generate build analysis
      const analysis = await esbuild.analyzeMetafile(result.metafile);
      console.log("📊 Bundle Analysis:\n", analysis);

      // Save metafile for further analysis
      fs.writeFileSync("build-meta.json", JSON.stringify(result.metafile, null, 2));
    }

    const buildTime = Date.now() - startTime;
    console.log(`✅ Production build completed in ${buildTime}ms`);

    await context.dispose();
    process.exit(0);
  } else {
    console.log("👀 Starting development watch mode with optimizations...");
    await context.watch();
  }
} catch (error) {
  console.error("❌ Build failed:", error);
  process.exit(1);
}
