/**
 * Integrity tests for RFC 36347daf Phase 2 — STATUS_UID_BY_ENUM and
 * CLASS_UID_TO_LABEL maps inside `GroundingExecutor`. These maps are not
 * verifiable against `kitelev/exoas-ems` vault fixtures (the submodule is
 * mounted only in vault-2025 / vault-exodev, not in this repo), so we
 * cover them with self-consistency invariants instead:
 *
 *  1. STATUS_UID_BY_ENUM has full coverage of `EffortStatus` enum (the
 *     `Record<EffortStatus, string>` type already guarantees this at
 *     compile time; this test makes it observable at runtime so accidental
 *     `as`-casts wouldn't silently bypass).
 *  2. Each value is a valid UUID v4 form (catches typos like swapped
 *     digits or missing hyphens).
 *  3. No collisions (UIDs are unique).
 *  4. CLASS_UID_TO_LABEL — same shape checks; values match
 *     `AssetClass.TASK / PROJECT / MEETING` (the only classes with
 *     default workflows in Phase 2).
 *
 * If a status TBox file is RENAMED in `kitelev/exoas-ems` without a TS
 * update, these tests still pass — drift surfaces at production write time
 * via the validate-wikilinks hook (defense-in-depth #3 in the map's
 * docstring). Phase 3 may add a true vault-fixture parity test once
 * `exoas-ems` is added as a submodule of this repo.
 */

import {
  STATUS_UID_BY_ENUM,
  CLASS_UID_TO_LABEL,
} from "../../../src/services/GroundingExecutor";
import { EffortStatus } from "../../../src/domain/constants/EffortStatus";
import { AssetClass } from "../../../src/domain/constants/AssetClass";

const UUID_V4_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
// Accept any valid UUID hex shape — some legacy status UIDs predate the
// v4 enforcement (e.g. EffortStatusBacklog `753a44d5-846c-4b82-9196-...`
// has version-nibble 4 but variant-nibble that is generated by other
// tooling). Use the relaxed shape for STATUS map; vault TBox files use
// the same UUID shape regardless of generator.
const UUID_RELAXED_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

describe("RFC 36347daf Phase 2 — STATUS_UID_BY_ENUM integrity", () => {
  it("covers every EffortStatus enum value", () => {
    const enumValues = Object.values(EffortStatus).sort();
    const mappedKeys = Object.keys(STATUS_UID_BY_ENUM).sort();
    expect(mappedKeys).toEqual(enumValues);
  });

  it("each UID is a valid UUID hex form", () => {
    for (const uid of Object.values(STATUS_UID_BY_ENUM)) {
      expect(uid).toMatch(UUID_RELAXED_REGEX);
    }
  });

  it("7 unique UIDs (no collisions)", () => {
    const uids = Object.values(STATUS_UID_BY_ENUM);
    expect(new Set(uids).size).toBe(7);
  });

  it("pins the known status UIDs (drift catches when this fixture lies)", () => {
    // Pinned to the vault TBox in `kitelev/exoas-ems`. Rename of any
    // status file in the vault requires updating this fixture AND
    // STATUS_UID_BY_ENUM. The integration parity test in Phase 3 will
    // walk the vault to verify these UIDs resolve to real files.
    expect(STATUS_UID_BY_ENUM[EffortStatus.DRAFT]).toBe(
      "c42245d0-01de-4c35-bfcf-d910445ea28e",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.BACKLOG]).toBe(
      "753a44d5-846c-4b82-9196-4fd9a4d48777",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.ANALYSIS]).toBe(
      "cde3525c-57ea-4efc-b477-2e7e7ccd3a1e",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.TODO]).toBe(
      "6a0e933a-6653-46f4-95ae-ed7508177c73",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.DOING]).toBe(
      "027e78f4-6e16-4b36-b8fb-5510507d5745",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.DONE]).toBe(
      "7b9b3116-7c3c-438c-9618-94fe301320a6",
    );
    expect(STATUS_UID_BY_ENUM[EffortStatus.TRASHED]).toBe(
      "5d14f18d-db2b-4847-9ac1-144cb93b2541",
    );
  });
});

describe("RFC 36347daf Phase 2 — CLASS_UID_TO_LABEL integrity", () => {
  it("each UID is a valid UUID hex form", () => {
    for (const uid of Object.keys(CLASS_UID_TO_LABEL)) {
      expect(uid).toMatch(UUID_RELAXED_REGEX);
    }
  });

  it("each label is a known AssetClass value", () => {
    const knownClasses = new Set(Object.values(AssetClass));
    for (const label of Object.values(CLASS_UID_TO_LABEL)) {
      expect(knownClasses.has(label as AssetClass)).toBe(true);
    }
  });

  it("3 unique UIDs (Task + Project + Meeting in Phase 2 scope)", () => {
    const uids = Object.keys(CLASS_UID_TO_LABEL);
    expect(new Set(uids).size).toBe(3);
  });

  it("covers Task, Project, Meeting (the classes with default workflows today)", () => {
    const labels = new Set(Object.values(CLASS_UID_TO_LABEL));
    expect(labels.has(AssetClass.TASK)).toBe(true);
    expect(labels.has(AssetClass.PROJECT)).toBe(true);
    expect(labels.has(AssetClass.MEETING)).toBe(true);
  });

  it("pins the known class UIDs", () => {
    // Inverse map for assertion (UIDs are keys in the source map).
    const labelToUid: Record<string, string> = {};
    for (const [uid, label] of Object.entries(CLASS_UID_TO_LABEL)) {
      labelToUid[label] = uid;
    }
    expect(labelToUid[AssetClass.TASK]).toBe(
      "1b20a8f0-d745-4e93-91db-4531b3df120e",
    );
    expect(labelToUid[AssetClass.PROJECT]).toBe(
      "7db5eeff-718a-49b0-8d2b-39b084a356e3",
    );
    expect(labelToUid[AssetClass.MEETING]).toBe(
      "1b0a5e34-dd7f-4ead-b43a-6c7c5a5ecaca",
    );
  });
});

// Suppress unused import lint when v4-only regex isn't applied above.
void UUID_V4_REGEX;
