import { describe, it, expect } from "@jest/globals";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

// RFC 94e520da Phase 1 / T1.5 — pin the audit fixture committed at
// docs/rfc-94e520da/starter-kit-grounding-status.json so any change to the
// starter-kit grounding inventory or the CLI service registry forces a
// conscious update of the audit (and the doc that depends on it).
//
// Fixture is regenerated by:
//   node scripts/audit-starter-kit-groundings.mjs \
//     --starter-kit ../exocortex-starter-kit \
//     --out docs/rfc-94e520da/starter-kit-grounding-status.json

const FIXTURE_PATH = resolve(
  __dirname,
  "..",
  "..",
  "..",
  "..",
  "..",
  "docs",
  "rfc-94e520da",
  "starter-kit-grounding-status.json",
);

interface Grounding {
  uid: string | null;
  label: string | null;
  path: string;
  type: string;
  serviceId: string | null;
  cliStatus: "real" | "stub" | "unregistered" | "drift";
}

interface Fixture {
  summary: {
    totalGroundings: number;
    byType: Record<string, number>;
    byCliStatus: Record<string, number>;
    serviceIdCounts: Record<string, number>;
  };
  groundings: Grounding[];
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

describe("RFC 94e520da T1.5 starter-kit grounding audit fixture", () => {
  it("contains exactly 48 groundings (RFC § Phase 1 reference count)", () => {
    expect(fixture.summary.totalGroundings).toBe(48);
    expect(fixture.groundings).toHaveLength(48);
  });

  it("classifies every grounding into a known cliStatus (no drift)", () => {
    const statuses = new Set(fixture.groundings.map((g) => g.cliStatus));
    expect(statuses.has("drift")).toBe(false);
    for (const g of fixture.groundings) {
      expect(["real", "stub", "unregistered"]).toContain(g.cliStatus);
    }
  });

  it("matches the expected type/cliStatus distribution", () => {
    expect(fixture.summary.byType).toEqual({
      service_call: 25,
      property_set: 16,
      property_delete: 4,
      composite: 2,
      create_instance: 1,
    });
    expect(fixture.summary.byCliStatus).toEqual({
      real: 38,
      stub: 3,
      unregistered: 7,
    });
  });

  it("non-service_call groundings are always classified as real", () => {
    for (const g of fixture.groundings) {
      if (g.type !== "service_call") {
        expect(g.cliStatus).toBe("real");
        expect(g.serviceId).toBeNull();
      }
    }
  });

  it("only the documented service ids appear in service_call groundings", () => {
    // T1.5 audit closure: locking the service-id surface area so a new
    // serviceId in starter-kit forces a conscious re-audit + this test
    // update + a CliServiceRegistryPopulator decision (real/stub/skip).
    const documentedRealIds = new Set([
      "createRelatedTask",
      "createRelatedProject",
      "archiveAsset",
      "planForEvening",
      "cleanProperties",
      "renameToUid",
      "repairFolder",
      "fixMissingLabel",
      "updateProperty",
    ]);
    const documentedStubIds = new Set(["createAsset"]);
    const documentedUnregisteredIds = new Set([
      "shiftDay",
      "planOnToday",
      "rollbackStatus",
      "incrementVotes",
      "createTaskForDailyNote",
      "copyLabelToAliases",
    ]);

    for (const g of fixture.groundings) {
      if (g.type !== "service_call") continue;
      const sid = g.serviceId;
      expect(sid).not.toBeNull();
      const set =
        g.cliStatus === "real"
          ? documentedRealIds
          : g.cliStatus === "stub"
            ? documentedStubIds
            : documentedUnregisteredIds;
      expect(set.has(sid as string)).toBe(true);
    }
  });
});
