import { describe, it, expect } from "@jest/globals";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));

// RFC 94e520da Phase 1 / T1.5 — pin the audit fixture committed at
// docs/rfc-94e520da/starter-kit-grounding-status.json so any change to the
// starter-kit grounding inventory or the CLI service registry forces a
// conscious update of the audit (and the doc that depends on it).
//
// Fixture is regenerated by:
//   node scripts/audit-starter-kit-groundings.mjs \
//     --starter-kit ../exocortex-starter-kit \
//     --out docs/rfc-94e520da/starter-kit-grounding-status.json

const FIXTURE_PATH = resolve(
  testDir,
  "..",
  "..",
  "..",
  "..",
  "..",
  "docs",
  "rfc-94e520da",
  "starter-kit-grounding-status.json",
);

interface Grounding {
  uid: string | null;
  label: string | null;
  path: string;
  type: string;
  serviceId: string | null;
  cliStatus: "real" | "stub" | "unregistered" | "drift";
}

interface Fixture {
  summary: {
    totalGroundings: number;
    byType: Record<string, number>;
    byCliStatus: Record<string, number>;
    serviceIdCounts: Record<string, number>;
  };
  groundings: Grounding[];
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

describe("RFC 94e520da T1.5 starter-kit grounding audit fixture", () => {
  it("contains exactly 48 groundings (RFC § Phase 1 reference count)", () => {
    expect(fixture.summary.totalGroundings).toBe(48);
    expect(fixture.groundings).toHaveLength(48);
  });

  it("classifies every grounding into a known cliStatus (no drift)", () => {
    const statuses = new Set(fixture.groundings.map((g) => g.cliStatus));
    expect(statuses.has("drift")).toBe(false);
    for (const g of fixture.groundings) {
      expect(["real", "stub", "unregistered"]).toContain(g.cliStatus);
    }
  });

  it("matches the expected type/cliStatus distribution", () => {
    // Issue #3132: grounding a85668fa-… migrated from service_call
    // (copyLabelToAliases) to declarative property_append (−1 service_call,
    // +1 property_append).
    // Issue #3134: groundings 0b104d75-… + 6ee56341-… migrated from
    // service_call (shiftDay) to declarative property_shift (−2 service_call,
    // +2 property_shift); grounding 506f031e-… migrated from service_call
    // (incrementVotes) to declarative property_increment (−1 service_call,
    // +1 property_increment). Net: 3 groundings move from
    // unregistered → real (24 → 21 service_call, 39 → 42 real,
    // 6 → 3 unregistered).
    // Issue #3136: grounding 22a6ba6b-… migrated from service_call
    // (planOnToday) to declarative property_set with new $todayStart token
    // (−1 service_call, +1 property_set). Grounding 4d8d5055-… migrated
    // from service_call (createTaskForDailyNote) to declarative
    // create_instance with new $targetFolder token + propertyDefaults JSON
    // literal (−1 service_call, +1 create_instance). Net: 2 groundings
    // move from unregistered → real (21 → 19 service_call, 42 → 44 real,
    // 3 → 1 unregistered).
    expect(fixture.summary.byType).toEqual({
      service_call: 19,
      property_set: 17,
      property_delete: 4,
      composite: 2,
      create_instance: 2,
      property_append: 1,
      property_increment: 1,
      property_shift: 2,
    });
    expect(fixture.summary.byCliStatus).toEqual({
      real: 44,
      stub: 3,
      unregistered: 1,
    });
  });

  it("non-service_call groundings are always classified as real", () => {
    for (const g of fixture.groundings) {
      if (g.type !== "service_call") {
        expect(g.cliStatus).toBe("real");
        expect(g.serviceId).toBeNull();
      }
    }
  });

  it("only the documented service ids appear in service_call groundings", () => {
    // T1.5 audit closure: locking the service-id surface area so a new
    // serviceId in starter-kit forces a conscious re-audit + this test
    // update + a CliServiceRegistryPopulator decision (real/stub/skip).
    const documentedRealIds = new Set([
      "createRelatedTask",
      "createRelatedProject",
      "archiveAsset",
      "planForEvening",
      "cleanProperties",
      "renameToUid",
      "repairFolder",
      "fixMissingLabel",
      "updateProperty",
    ]);
    const documentedStubIds = new Set(["createAsset"]);
    const documentedUnregisteredIds = new Set([
      "rollbackStatus",
      // copyLabelToAliases removed in Issue #3132 — grounding migrated to
      // declarative property_append (no longer a service_call).
      // shiftDay (×2) + incrementVotes (×1) removed in Issue #3134 —
      // groundings migrated to declarative property_shift /
      // property_increment (RFC 18407cb2 Path B).
      // planOnToday + createTaskForDailyNote removed in Issue #3136 —
      // groundings migrated to declarative property_set (with $todayStart)
      // + create_instance (with $targetFolder + propertyDefaults). Only
      // rollbackStatus remains — Q3.a documented temporal-stack pop.
    ]);

    for (const g of fixture.groundings) {
      if (g.type !== "service_call") continue;
      const sid = g.serviceId;
      expect(sid).not.toBeNull();
      const set =
        g.cliStatus === "real"
          ? documentedRealIds
          : g.cliStatus === "stub"
            ? documentedStubIds
            : documentedUnregisteredIds;
      expect(set.has(sid as string)).toBe(true);
    }
  });
});
